language: csharp
mono: none
dotnet: 2.1
before_install:
  - sudo apt-get install dotnet-sdk-3.1
script:
  - dotnet restore ./src/Quartz.Extensions.DependencyInjection/
  - dotnet build ./src/Quartz.Extensions.DependencyInjection/